StudentRegistration/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static      
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('students.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import include,path
from .views import studentregistration, registrationpage, studentslist, edit_student_form

urlpatterns = [
    path('',registrationpage,name="registrationform"),
    path('add-registration-form/',studentregistration,name="studentregister"),
    path('registered_students/',studentslist,name="list_students"),
    path('editform/<int:pk>',edit_student_form,name='edit_student_form'),
]

students/models.py
from django.db import models

# Create your models here.

gender = (
    ('MALE','MALE'),
    ('FEMALE','FEMALE'),
)

student_class = (
    ('8','8'),
    ('9','9'),
    ('10','10'),
    ('11','11'),
    ('12','12'),
)

student_divisions = (
    ('A','A'),
    ('B','B'),
    ('C','C'),
    ('D','D'),
)

class Students(models.Model):
    firstname   = models.CharField(max_length=100, blank=False, null=False)
    middlename  = models.CharField(max_length=100, blank=True, null=True)
    lastname    = models.CharField(max_length=100, blank=False, null=False)
    dob         = models.DateField(auto_now=False,auto_now_add=False,blank=False,null=False)
    age         = models.CharField(max_length=2,blank=False, null=False)
    email       = models.EmailField(max_length=100,blank=False,null=False)
    contact     = models.CharField(max_length=10,blank=False,null=False)
    gender      = models.CharField(choices=gender,blank=False,null=False,max_length=20)
    standard    = models.CharField(choices=student_class,blank=False,null=False,max_length=10)
    division    = models.CharField(choices=student_divisions,blank=False,null=False,max_length=10)
    father_name = models.CharField(max_length=100,blank=False,null=False)
    mother_name = models.CharField(max_length=100,blank=False,null=False)
    address     = models.TextField(max_length=1000,blank=False,null=False)
    photo       = models.ImageField(upload_to='student_photos',max_length=100,blank=False,null=False)

    def __str__(self):
        return self.firstname

students/forms.py
from django import forms
from .models import Students

class StudentForm(forms.ModelForm):
    dob = forms.DateField(input_formats=['%d-%m-%Y'],widget=forms.DateInput(attrs={'class':'date-pick'},format='%d-%m-%Y'))
    class Meta:
        model = Students
        fields = ('firstname','middlename','lastname','dob','age','email','contact','gender','standard',
        'division','father_name','mother_name','address','photo')
        widgets = {
            'contact':forms.TextInput(attrs={'type':'text','max_length':'10','class':'only_allow_number'}),
            'age':forms.TextInput(attrs={'type':'text','class':'only_allow_number'}),
        } 
        help_texts = {
            'photo': 'Please upload passport size photo. Maximum resolution 1260 * 990 pixels.',
        }

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        self.fields['dob'].label = "Date of Birth"
        self.fields['firstname'].label = 'First Name'
        self.fields['middlename'].label = 'Middle Name'
        self.fields['lastname'].label = 'Last Name'
        self.fields['father_name'].label = 'Name of Father'
        self.fields['mother_name'].label = 'Name of Mother'

class DropdownForm(forms.ModelForm):
    class Meta:
        model = Students
        fields  = ['gender','standard','division']

students/views.py
from django.shortcuts import render,redirect
from django.views import View
from .forms import StudentForm,DropdownForm
from django.contrib import messages
from .models import Students
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import operator
import functools
from django.db.models import Q
from datetime import datetime
# Create your views here.

def registrationpage(request):
    student_form = StudentForm()
    return render(request,"registration_form/registration_form.html",{"student_form":student_form})

def studentregistration(request):
    studentform = StudentForm(request.POST,request.FILES or None) 
    if studentform.is_valid():
        studentform.save()
        messages.success(request,"Form Submitted Successfully !")
        return redirect('registrationform')

def studentslist(request):
    students = Students.objects.all().order_by('-id')
    dropform = DropdownForm()
    search = request.GET.get('search')
    st_gender = request.GET.get('gender')
    st_standard = request.GET.get('standard')
    st_division = request.GET.get('division')
    
    filters = []
    if st_gender:
        case1 = Q(gender=st_gender)
        filters.append(case1)
    if st_standard:
        case2 = Q(standard=st_standard)
        filters.append(case2)
    if st_division:
        case3 = Q(division=st_division)
        filters.append(case3)
    if st_gender or st_standard or st_division:
        filters=functools.reduce(operator.and_,filters)
        students = students.filter(filters)

    if search:
        students = students.filter(Q(firstname__icontains=search)|Q(middlename__icontains=search)|Q(lastname__icontains=search)|Q(dob__icontains=search)|Q(father_name__icontains=search)|Q(mother_name__icontains=search)|Q(email__icontains=search)|Q(contact__icontains=search)|Q(address__icontains=search))

    paginator = Paginator(students,5) #Pagination
    page = request.GET.get('page')
    try:
        student_pg = paginator.page(page)
    except PageNotAnInteger:
        student_pg = paginator.page(1)
    except EmptyPage:
        student_pg = paginator.page(paginator.num_pages)
    return render(request,"registered_students/registered_students.html",{"students":student_pg,"dropform":dropform,'gender':st_gender,'standard':st_standard,'division':st_division,'search':search})

def edit_student_form(request,pk):
    student = Students.objects.get(pk=pk)
    edit_student_form = StudentForm(instance=student)
    
    if request.method == "POST":
        section = request.POST['section']
        if section == 'edit':
            edit_form = StudentForm(request.POST,request.FILES or None,instance=student)
            if edit_form.is_valid():
            
                edit_form.save()
                
                messages.success(request,"Changes Saved !")
                return redirect('list_students')

        if section == 'delete':
            student = Students.objects.get(pk=pk)
            student.delete()
            messages.success(request,"Student Deleted successfully !")
            return redirect('list_students')
    return render(request,"registered_students/edit_student.html",{'edit_student_form':edit_student_form,'student':student})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="shortcut icon" type="image/ico" href="{% static 'files/images/favicon.ico' %}?v=1" />
  <title>STUDENT REGISTRATION FORM</title>
  <link href="{% static 'files/plugins/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'files/css/custom.css' %}?v=4" rel="stylesheet" type="text/css" /> 
  <link href="{% static 'files/fonts/web-fonts/web-fonts.css' %}?v=1" rel="stylesheet" type="text/css" />
  <link href="{% static 'files/fonts/font-awesome/css/font-awesome.min.css' %}?v=1" rel="stylesheet" type="text/css" />
  <link href="{% static 'files/plugins/side-menu/side-menu.css' %}?v=3" rel="stylesheet" type="text/css" />
  <link href="{% static 'files/plugins/datepicker/jquery-ui.css' %}?v=1" rel="stylesheet" type="text/css" />
  <link href="{% static 'files/plugins/chosen-select/chosen.css' %}?v=1" rel="stylesheet" type="text/css" />
  <script src="{% static 'files/js/jquery-3.3.1.min.js' %}?v=1" type="text/javascript"></script>
  {% block xtra_css %}
  {% endblock %}
 </head>
<body>
 
    <div class="pre-loader">
      <div class="loader-icon"></div>
      <span>Loading...</span>
    </div><!-- pre-loader -->

     {% block content %}
     {% endblock %}

</div><!-- container-fluid, main-body -->

 <!-- bootstrap --> 
 <script src="{% static 'files/plugins/bootstrap4/js/bootstrap.min.js' %}?v=1" type="text/javascript"></script>
 <!-- side-menu -->
 <script src="{% static 'files/plugins/side-menu/side-menu.js' %}?v=1" type="text/javascript"></script>
 <!-- datepicker -->
 <script src="{% static 'files/plugins/datepicker/jquery-ui.js' %}?v=1" type="text/javascript"></script>
 <!-- chosen-select -->
 <script src="{% static 'files/plugins/chosen-select/chosen.jquery.js' %}?v=1" type="text/javascript"></script>
 <!-- swipe-menu -->
 <script src="{% static 'files/plugins/swipe-menu/swipe-menu.js' %}?v=1" type="text/javascript"></script>
 <!-- pagination -->
 <input type="hidden" id="max_rows">
 <script src="{% static 'files/plugins/pagination/pagination_frontend.js' %}?v=1" type="text/javascript"></script>
 <!-- common js -->
 <script src="{% static 'files/js/custom.js' %}?v=3" type="text/javascript"></script>
   {% block javascript %}
   {% endblock %}
   {% include 'common_messages.html' %}
</body>
</html>

templates/common/header.html
{% load static %}
<!-- header -->
<header class="header">
  <div class="container-fluid">

    <div class="row">
      <!-- left -->
      <div class="col-7 left">

        <a href="" class="a-logo">
          <h1>STUDENT REGISTRATION</h1>
        </a>

        <!-- sidebar-toggle -->
        <a data-toggle="body" class="sidebar-toggle">
          <span></span>
          <span></span>
          <span></span>
        </a>
        <div class="swipe-area-btn"></div>
      </div>

    </div>
  </div>
</header>
<!-- /header -->

<!-- side-menu -->
<aside id="sidebar">

  <!-- sidebar-toggle -->
  <a data-toggle="body" class="sidebar-toggle"></a>

  <ul class="sidebar-menu">
    <li>
      <a href="/">  
        <i class="fa fa-circle-thin" aria-hidden="true"></i>
        <span>Registration Form</span>
      </a>
    </li>
    <li>
      <a href="/registered_students/">  
        <i class="fa fa-circle-thin" aria-hidden="true"></i>
        <span>View Students</span>
      </a>
    </li>
  </ul>
</aside>
<!-- /side-menu -->


<div class="container-fluid main-body">

templates/common_messages.html
 {% load static %}
 {% block xtra_css %}
  <link href="{% static 'files/css/message_wrapper.css' %}?v=18" rel="stylesheet" type="text/css" /> 
  {% endblock %}
    {% if messages %}
	{% for message in messages %}
	{% if forloop.counter0 == 0 %}
    <div class="message_wrapper">
        <div class="message_common {{ message.tags }}">
		 <i class="fa fa-times" aria-hidden="true" onclick="close_message();" title="Close"></i>
         <h3>
		 <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
		 <i class="fa fa-check" aria-hidden="true"></i>
		 {% autoescape off %}{{ message }}{% endautoescape %}</h3>
        </div>
	</div>
	{% endif %}
	{% endfor %}
    <script>
    function close_message()
        {
		$('.message_wrapper').hide();
        }
    $(window).ready(function(){
        $('.message_wrapper').addClass('display_class');
        AutoCloseDialogBox(3000);
            return false;
     }); 
     function AutoCloseDialogBox(WaitSeconds) {
            //Auto Close Dialog Box after few seconds
            setTimeout(
                function () {
                    $(".message_wrapper").hide();
                }, WaitSeconds);
        }
    </script>
    {% endif %}

templates/registered_students/edit_student.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="app_form app_form_edit">
{% include 'common/header.html' %}

<!-- Edit Form -->
<div class="row">
    <div class="col-12">
      <div class="page-form page-form-center">
      <form method="POST" action="{% url 'edit_student_form' student.id %}" enctype="multipart/form-data">{% csrf_token %}     
      <input type="hidden" name="section" value="edit" />
      <div class="page-form-head">
          <h1>Edit Application</h1>
          {% if student.photo %}
          <img class="choose_img_show" src="{{ student.photo.url }}" >
          {% else %}
          <img class="choose_img_show" src="{% static 'files/images/profile-icon.png' %}" >
          {% endif %}
       </div>
       <div class="page-body">
          <table>
              {{edit_student_form.as_table}}
          </table>
         </div>
         <div class="page-footer text-center">
            <button type="button" class="delete-btn" data-toggle="modal" data-target="#delete_data_popup">Delete</button>
            <button type="button" class="primary-btn" onclick="submitAnyForm(this);">Update</button>
         </div>
        </form>
     </div>   
    </div>
  </div>

<!-- delete_data_popup-->
<div class="modal fade pop-up" id="delete_data_popup" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
       <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
         <input type="hidden" name="section" value="delete" />
        <div class="body delete-popup">
          <div class="modal-header">
            <h1>Delete Student</h1>  
          </div>
          <div class="modal-body"> 
            <div class="row">
              <div class="col-12">
                <h4>Are you sure you want to delete <b>{{student.firstname}} {{student.lastname}}</b> ?</h4>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="close-btn" data-dismiss="modal">Close</button>
            <button type="button" class="primary-btn" onclick="submitAnyForm(this);">Delete</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- /delete_data_popup-->

</div>
{% endblock %}

templates/registered_students/registered_students.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="applicants">
  {% include 'common/header.html' %}

  <div class="row page-head">
    <div class="col-md-6"> 
      <h1>REGISTERED STUDENTS</h1>
    </div>

    <div class="col-md-6"> 
      <!-- search -->
      <form class="search">
          <input type="search" name="search" id="search" placeholder="search for" value="{{search|default_if_none:""}}" onkeypress="if(event.keyCode==13)set_params_go({})" maxlength="100" />
      </form>
    </div>
  </div>

  <!-- Table Filters -->
  <div class="row">
    <div class="col-12">
      <div class="filter-by">
       <a class="a-btn clear-btn" href="/registered_students/">Reset Filter</a>
        <form>
         {% for field in dropform %}
          <div class="div-col">
             {{ field.errors }}
             {{ field.label_tag }} {{ field }}
             {% if field.help_text %}
             <p class="help">{{ field.help_text|safe }}</p>
             {% endif %}
          </div>
        {% endfor %}
      </form>
      </div>
    </div>
  </div>

  <input type="hidden" id="gen" value="{{gender|default_if_none:"no"}}" />
  <input type="hidden" id="std" value="{{standard|default_if_none:"no"}}" />
  <input type="hidden" id="div" value="{{division|default_if_none:"no"}}" />

  <!-- Student Data Table -->
<div class="row">
    <div class="col-12">
            <div class="table-responsive">
              <div class="common-table">
               <table class="table frontend_pagination">
                  <thead>
                    <tr class="tr-head">
                      <th class="xs-tcol">Sl.No</th>
                      <th class="m-tcol">First Name</th>
                      <th class="m-tcol">Middle Name</th>
                      <th class="m-tcol">Last Name</th>
                      <th class="s-tcol">Date of Birth</th>
                      <th class="s-tcol">Age</th>
                      <th class="s-tcol">Gender</th>
                      <th class="m-tcol">Father's Name</th>
                      <th class="m-tcol">Mother's Name</th>
                      <th class="l-tcol">Address</th>
                      <th class="m-tcol">Email</th>
                      <th class="s-tcol">Contact No.</th>
                      <th class="s-tcol">Class</th>
                      <th class="s-tcol print-hide">Photo</th>
                      <th class="s-tcol">Edit</th>
                    </tr>
                  </thead>
                  <tbody>
                   {% for student in students %}
                    <tr class="tr-body"> 
                        <td class="xs-tcol">{{forloop.counter0|add:students.start_index}}</td>
                        <td class="m-tcol">{{student.firstname|default_if_none:'-'}}</td>
                        <td class="m-tcol">{{student.middlename|default_if_none:'-'}}</td>
                        <td class="m-tcol">{{student.lastname|default_if_none:'-'}}</td>
                        <td class="s-tcol">{{student.dob|date:'d-m-Y'|default_if_none:'-'}}</td>
                        <td class="s-tcol">{{student.age|default_if_none:'-'}}</td>
                        <td class="s-tcol">{{student.gender|default_if_none:'-'}}</td>
                        <td class="m-tcol">{{student.father_name|default_if_none:'-'}}</td>
                        <td class="m-tcol">{{student.mother_name|default_if_none:'-'}}</td>
                        <td class="l-tcol">{{student.address|default_if_none:'-'}}</td>
                        <td class="m-tcol">{{student.email|default_if_none:'-'}}</td>
                        <td class="s-tcol">{{student.contact|default_if_none:'-'}}</td>
                        <td class="s-tcol">{{student.standard|default_if_none:'-'}} {{student.division|default_if_none:'-'}}</td>
                        <td class="s-tcol print-hide">
                        {% if student.photo %}
                          <img src="{{ student.photo.url }}" class="img_expand_btn" data-id="{{student.id}}" data-imgurl="{{student.photo.url}}">
                        {% else %}
                        -
                        {% endif %}
                        </td>
                        <td class="s-tcol"><a href="{% url 'edit_student_form' student.id %}" class="a-btn edit-btn">Edit</a></td>
                    </tr>
                    {% empty %}
                    <!-- no-data -->
                    <tr class="no-data">
                      <td colspan="15">No Data</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table> 
                <div class="paginated">
                  {% if students.has_previous %}
                      <a href="?page={{ students.previous_page_number }}&gender={{gender|default_if_none:""}}&standard={{standard|default_if_none:""}}&division={{division|default_if_none:""}}&search={{search|default_if_none:""}}"><button class="page-previous">Previous</button></a>
                  {% else %}
                      <button class="page-previous page-disabled">Previous</button>
                  {% endif %}
                  <div class="current">
                      Page {{ students.number }} of {{ students.paginator.num_pages }}.
                  </div>
                    {% if students.has_next %}
                      <a href="?page={{ students.next_page_number }}&gender={{gender|default_if_none:""}}&standard={{hotel_type1|default_if_none:""}}&division={{division|default_if_none:""}}&search={{search|default_if_none:""}}"><button class="page-next">Next</button></a>
                    {% else %}
                      <button class="page-next page-disabled">Next</button>
                    {% endif %}           
                  </div>
              </div>
          </div>
    </div>
  </div>

  <!-- img_expand_popup -->
  <div class="modal fade pop-up" id="img_expand_popup" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
          <div class="body img-expand-popup">
            <div class="modal-header">
              <button type="button" class="close-btn" data-dismiss="modal" aria-label="Close">
                <i class="fa fa-times" aria-hidden="true"></i>
              </button>
            </div>
            <div class="modal-body">
              <div class="row"> 
                <div class="col-12">
                    <input type="hidden" id="img_expand_id" />
                    <img id="img_expand_url" class="img-fluid">
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
 <!-- /img_expand_popup -->

</div>

{% endblock %}
{% block javascript %}
<script type="text/javascript">

// search and filter 
function set_params_go(args)
{
var url='{% url 'list_students' %}';
var params={gender:$('#id_gender').val(),standard:$('#id_standard').val(),division:$('#id_division').val(),search:$('#search').val()
};
for(key in args)
	params[key]=args[key];
var query='';
for(key in params)
	if(params[key])
		query+='&'+key+'='+params[key].toString();
query=query.replace('&','?');
console.log(query);
window.location.href=url+query;
}

// gender dropdown change
$(document).on('change', '#id_gender', function(e){
  set_params_go({});
});

// standard dropdown change
$(document).on('change', '#id_standard', function(e){
  set_params_go({});
})

// division dropdown change
$(document).on('change', '#id_division', function(e){
  set_params_go({});
})

// Hold selected option in dropdowns
$(document).ready(function(){
  var gen = $('#gen').val();
  var std = $('#std').val();
  var div = $('#div').val();

  if (gen !== 'no'){
    $('#id_gender').val(gen).attr("selected","selected");
    console.log('war');
  }

  if (std !== 'no'){
    $('#id_standard').val(std).attr("selected","selected");
    console.log('war2');
  }

  if (div !== 'no'){
    $('#id_division').val(div).attr("selected","selected");
  }

});

</script>
{% endblock %}

templates/registration_form/registration_form.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<!-- Registration Form -->
<div class="app_form app_form_add">
    {% include 'common/header.html' %}
<div class="row">
    <div class="col-12">
      <div class="page-form page-form-center">
     <form method="POST" action="{% url 'studentregister'%}" enctype="multipart/form-data" >{% csrf_token %}
      <div class="page-form-head">
          <h1>Registration Form</h1>
       </div>
       <div class="page-body">
          <table>
             {{student_form.as_table}}
          </table>
         </div>
         <div class="page-footer text-center">
            <button type="button" class="primary-btn" onclick="submitAnyForm(this);">Submit Form</button>
         </div>
        </form>
     </div>   
    </div>
  </div>
</div>
<!-- /Registration_form -->

{% endblock %}